### ISSUE TITLE
importing ray raise a AttributeError on sys.stdout()

### ISSUE THREAD

**Issue by hallavar** [netsharecmu/NetShare#17]
Hello,

I'm trying to implement a simple generation of netflow from ugr16 dataset. I'm on linux and python3.6

My config.json is

```
{
    "global_config": {
        "original_data_file": "../traces/ugr16/raw.csv",
        "dataset_type": "netflow",
        "n_chunks": 10,
        "dp": false,
        "max_flow_len": false #to avoid the raising of an attribute error in netshare_pre_post_processor.py
    },
    "default": "netflow.json"
}
```

My driver.py is
```

from netshare import Generator
if __name__ == '__main__':
    # configuration file
    generator = Generator(config="netflow/config_example_netflow_nodp.json")

    # `work_folder` should not exist o/w an overwrite error will be thrown.
    # Please set the `worker_folder` as *absolute path*
    # if you are using Ray with multi-machine setup
    # since Ray has bugs when dealing with relative paths.
    
    #generator.visualize(work_folder='../results/vis_test')
    generator.train_and_generate(work_folder='../results/vis_test/')

```

After building all the chunk, the program starts working on the first chunk and raise an Attribute error linked to ray (wich is not use in the program)

The error Traceback is
```

Traceback (most recent call last):
  File "/srv/tempdd/aschoen/NetShare/netshare/pre_post_processors/pre_post_processor.py", line 29, in pre_process
    log_folder=log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/pre_post_processors/netshare/netshare_pre_post_processor.py", line 406, in _pre_process
    flowkeys_chunkidx=flowkeys_chunkidx,
  File "/srv/tempdd/aschoen/NetShare/netshare/ray/remote.py", line 25, in remote
    import ray
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/__init__.py", line 169, in <module>
    from ray import autoscaler  # noqa:E402
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/__init__.py", line 1, in <module>
    from ray.autoscaler import sdk
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/sdk/__init__.py", line 1, in <module>
    from ray.autoscaler.sdk.sdk import (
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/sdk/sdk.py", line 9, in <module>
    from ray.autoscaler._private import commands
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/commands.py", line 24, in <module>
    from ray.autoscaler._private import subprocess_output_util as cmd_output_util
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/subprocess_output_util.py", line 8, in <module>
    from ray.autoscaler._private.cli_logger import cf, cli_logger
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/cli_logger.py", line 61, in <module>
    import colorful as _cf
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/__init__.py", line 133, in <module>
    sys.modules[__name__] = ColorfulModule(Colorful(), __name__)
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/core.py", line 342, in __init__
    colormode = terminal.detect_color_support(env=os.environ)
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/terminal.py", line 48, in detect_color_support
    if not sys.stdout.isatty():
```

I think it is the import of ray in the RemoteFunctionWrapper of remote.py which is causing this fault. Is there a way to ignore this wrapper in your code by giving a specific argument to the json file ?

If you have any advice, I would really appreciate.

Good luck for your big merge ;)

Adrien

**Comment by saart** [comment]
Dear Adrien,
Thank you for opening this issue.

Blaming `ray` is interesting. 
Can you please try to change the configuration to disable `ray` (it's in the `driver.py` file, change to `ray.config.enabled = False`) and check if the error still happens?
Here's another possible cause: do you use databricks? https://stackoverflow.com/questions/47069239/consolebuffer-object-has-no-attribute-isatty
Moreover, can you please attach the entire error message?

Saar

**Comment by hallavar** [comment]
Hello,

This is the global stdout :

```
(NetShare-env) aschoen@igrida14-01:/srv/tempdd/aschoen/NetShare/examples$ python3 driver.py 
NetsharePrePostProcessor._pre_process
../traces/ugr16/raw.csv
Training word2vec model from scratch...
Training Word2Vec model from scratch...
Word2Vec model is saved at ../results/vis_test/pre_processed_data/word2vec_vecSize_10.model
Using fixed_time
Chunk_id: 0, # of pkts/records: 659
Chunk_id: 1, # of pkts/records: 1092
Chunk_id: 2, # of pkts/records: 102214
Chunk_id: 3, # of pkts/records: 125351
Chunk_id: 4, # of pkts/records: 127242
Chunk_id: 5, # of pkts/records: 131047
Chunk_id: 6, # of pkts/records: 133070
Chunk_id: 7, # of pkts/records: 130395
Chunk_id: 8, # of pkts/records: 123788
Chunk_id: 9, # of pkts/records: 125142
df_chunk_cnt_validation: 1000000
Chunk time: 134.2636 seconds
compute flowkey-chunk list from scratch...
processing chunk 1/10, # of flows: 653
processing chunk 2/10, # of flows: 1085
processing chunk 3/10, # of flows: 89308
processing chunk 4/10, # of flows: 109210
processing chunk 5/10, # of flows: 109674
processing chunk 6/10, # of flows: 114892
processing chunk 7/10, # of flows: 116132
processing chunk 8/10, # of flows: 113368
processing chunk 9/10, # of flows: 107063
processing chunk 10/10, # of flows: 108010
# of total flows: 793801
# of total flows (sanity check): 793801
# of flows cross chunk (of total flows): 48169 (6.068145542774574%)
# of non-continuous flows: 5153
chunk_id: 0, max_flow_len: 2
chunk_id: 1, max_flow_len: 3
chunk_id: 2, max_flow_len: 30
chunk_id: 3, max_flow_len: 16
chunk_id: 4, max_flow_len: 26
chunk_id: 5, max_flow_len: 24
chunk_id: 6, max_flow_len: 16
chunk_id: 7, max_flow_len: 12
chunk_id: 8, max_flow_len: 15
chunk_id: 9, max_flow_len: 34
global max flow len: 34
Top 10 per-chunk flow length: [18, 19, 24, 25, 25, 26, 26, 27, 30, 34]
0it [00:00, ?it/s]
Chunk_id: 0
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "/srv/tempdd/aschoen/NetShare/netshare/pre_post_processors/pre_post_processor.py", line 29, in pre_process
    log_folder=log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/pre_post_processors/netshare/netshare_pre_post_processor.py", line 406, in _pre_process
    flowkeys_chunkidx=flowkeys_chunkidx,
  File "/srv/tempdd/aschoen/NetShare/netshare/ray/remote.py", line 25, in remote
    import ray
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/__init__.py", line 169, in <module>
    from ray import autoscaler  # noqa:E402
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/__init__.py", line 1, in <module>
    from ray.autoscaler import sdk
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/sdk/__init__.py", line 1, in <module>
    from ray.autoscaler.sdk.sdk import (
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/sdk/sdk.py", line 9, in <module>
    from ray.autoscaler._private import commands
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/commands.py", line 24, in <module>
    from ray.autoscaler._private import subprocess_output_util as cmd_output_util
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/subprocess_output_util.py", line 8, in <module>
    from ray.autoscaler._private.cli_logger import cf, cli_logger
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/cli_logger.py", line 61, in <module>
    import colorful as _cf
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/__init__.py", line 133, in <module>
    sys.modules[__name__] = ColorfulModule(Colorful(), __name__)
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/core.py", line 342, in __init__
    colormode = terminal.detect_color_support(env=os.environ)
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/terminal.py", line 48, in detect_color_support
    if not sys.stdout.isatty():
AttributeError: 'DuplicateWriter' object has no attribute 'isatty'
Traceback (most recent call last):
  File "example_netflow.py", line 13, in <module>
    generator.train_and_generate(work_folder='../results/vis_test/')
  File "/srv/tempdd/aschoen/NetShare/netshare/generators/generator.py", line 203, in train_and_generate
    if not self.train(work_folder):
  File "/srv/tempdd/aschoen/NetShare/netshare/generators/generator.py", line 189, in train
    work_folder)):
  File "/srv/tempdd/aschoen/NetShare/netshare/generators/generator.py", line 100, in _pre_process
    log_folder=log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/pre_post_processors/pre_post_processor.py", line 29, in pre_process
    log_folder=log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/pre_post_processors/netshare/netshare_pre_post_processor.py", line 406, in _pre_process
    flowkeys_chunkidx=flowkeys_chunkidx,
  File "/srv/tempdd/aschoen/NetShare/netshare/ray/remote.py", line 25, in remote
    import ray
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/__init__.py", line 169, in <module>
    from ray import autoscaler  # noqa:E402
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/__init__.py", line 1, in <module>
    from ray.autoscaler import sdk
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/sdk/__init__.py", line 1, in <module>
    from ray.autoscaler.sdk.sdk import (
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/sdk/sdk.py", line 9, in <module>
    from ray.autoscaler._private import commands
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/commands.py", line 24, in <module>
    from ray.autoscaler._private import subprocess_output_util as cmd_output_util
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/subprocess_output_util.py", line 8, in <module>
    from ray.autoscaler._private.cli_logger import cf, cli_logger
  File "/udd/aschoen/.local/lib/python3.6/site-packages/ray/autoscaler/_private/cli_logger.py", line 61, in <module>
    import colorful as _cf
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/__init__.py", line 133, in <module>
    sys.modules[__name__] = ColorfulModule(Colorful(), __name__)
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/core.py", line 342, in __init__
    colormode = terminal.detect_color_support(env=os.environ)
  File "/udd/aschoen/.conda/envs/NetShare-env/lib/python3.6/site-packages/colorful/terminal.py", line 48, in detect_color_support
    if not sys.stdout.isatty():
AttributeError: 'DuplicateWriter' object has no attribute 'isatty'
```

Indeed, when indicating `ray.config.enabled = False`, The training is executed correctly.

Thank you very much for your quick answer, and good luck for the future. You can close the issue.

**Comment by sniperyyc** [comment]
Thank you very much, glad to hear that!
