### ISSUE TITLE
Netflow Training and generation ValueError: Pretrain_dir {} does not exist!

### ISSUE THREAD

**Issue by hallavar** [netsharecmu/NetShare#18]
Hello,
Thank you for your work. I'm interested in implementing your solution for netflow traffic generation.
Unfortunately, at the end of the chunk0 training, I experience the following error (I copy/paste the last part of the stdout/err, because the entire would be too long).

```
Stop data_loader #0: True
Stop data_loader #1: True
data loader ended
-------------
data loader ended
-------------
data loader endeddata loader ended
-------------

-------------
data loader ended
-------------
Stop data_loader #2: True
Stop data_loader #3: True
Stop data_loader #4: True
data loader ended
-------------
Stop data_loader #5: True
Stop data_loader #6: True
Stop data_loader #7: True
Stop data_loader #8: True
Stop data_loader #9: True
-------------
Finish launching chunk0 experiments ...
Start waiting for chunk0 from config_group_id 0experiments finished ...
Traceback (most recent call last):
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/model_manager.py", line 34, in train
    model_config=model_config)
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/netshare_manager/netshare_manager.py", line 42, in _train
    log_folder=log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/ray/remote.py", line 34, in remote
    return ResultWrapper(self._ray_args[0](*args, **kwargs))
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/netshare_manager/train_helper.py", line 104, in _train_specific_config_group
    log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/netshare_manager/train_helper.py", line 24, in _launch_other_chunks_training
    raise ValueError("Pretrain_dir {} does not exist!")
ValueError: Pretrain_dir {} does not exist!
Traceback (most recent call last):
  File "example_netflow.py", line 15, in <module>
    generator.train_and_generate(work_folder='../results/vis_test/')
  File "/srv/tempdd/aschoen/NetShare/netshare/generators/generator.py", line 203, in train_and_generate
    if not self.train(work_folder):
  File "/srv/tempdd/aschoen/NetShare/netshare/generators/generator.py", line 196, in train
    log_folder=self._get_model_log_folder(work_folder)):
  File "/srv/tempdd/aschoen/NetShare/netshare/generators/generator.py", line 122, in _train
    model_config=self._model_config)
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/model_manager.py", line 34, in train
    model_config=model_config)
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/netshare_manager/netshare_manager.py", line 42, in _train
    log_folder=log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/ray/remote.py", line 34, in remote
    return ResultWrapper(self._ray_args[0](*args, **kwargs))
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/netshare_manager/train_helper.py", line 104, in _train_specific_config_group
    log_folder)
  File "/srv/tempdd/aschoen/NetShare/netshare/model_managers/netshare_manager/train_helper.py", line 24, in _launch_other_chunks_training
    raise ValueError("Pretrain_dir {} does not exist!")
ValueError: Pretrain_dir {} does not exist!
```

Maybe it has something to do with my config file and especially the part with the pretrain_dir argument. I've tryed with pretrain_dir = null or pretrain_dir = '/path/to/a/directory/on/my/computer' but both return me this error.

This is my complete config file
```

{
    "global_config": {
        "overwrite": true,
        "original_data_file": "../traces/ugr16/raw.csv",
        "dataset_type": "netflow",
        "n_chunks": 10,
        "dp": false,
        "word2vec_vecSize": 10,
        "timestamp": "interarrival",
        "truncate": "per_chunk",
        "max_flow_len": false 
    },
    "pre_post_processor": {
        "class": "NetsharePrePostProcessor",
        "config": {
            "norm_option": 0,
            "split_name": "multichunk_dep_v2",
            "df2chunks": "fixed_time",
            "full_IP_header": true,
            "encode_IP": "bit"
        }
    },
    "model_manager": {
        "class": "NetShareManager",
        "config": {
            "pretrain_dir": null,
            "skip_chunk0_train": false,
            "pretrain_non_dp": true,
            "pretrain_non_dp_reduce_time": 4.0,
            "pretrain_dp": false,
            "run": 0
        }
    },
    "model": {
        "class": "DoppelGANgerTFModel",
        "config": {
            "batch_size": 1000,
            "sample_len": [
                1,
                5,
                10
            ],
            "sample_len_expand": true,
            "iteration": 500,
            "vis_freq": 2001,
            "vis_num_sample": 5,
            "d_rounds": 5,
            "g_rounds": 1,
            "num_packing": 1,
            "noise": true,
            "attr_noise_type": "normal",
            "feature_noise_type": "normal",
            "rnn_mlp_num_layers": 0,
            "feed_back": false,
            "g_lr": 0.0001,
            "d_lr": 0.0001,
            "d_gp_coe": 10.0,
            "gen_feature_num_layers": 1,
            "gen_feature_num_units": 100,
            "gen_attribute_num_layers": 5,
            "gen_attribute_num_units": 512,
            "disc_num_layers": 5,
            "disc_num_units": 512,
            "initial_state": "random",
            "leaky_relu": false,
            "attr_d_lr": 0.0001,
            "attr_d_gp_coe": 10.0,
            "g_attr_d_coe": 1.0,
            "attr_disc_num_layers": 5,
            "attr_disc_num_units": 512,
            "aux_disc": true,
            "self_norm": false,
            "fix_feature_network": false,
            "debug": false,
            "combined_disc": true,
            "use_gt_lengths": false,
            "use_uniform_lengths": false,
            "num_cores": null,
            "sn_mode": null,
            "scale": 1.0,
            "extra_checkpoint_freq": 20000,
            "epoch_checkpoint_freq": 1000,
            "dp_noise_multiplier": null,
            "dp_l2_norm_clip": null
        }
    }
}


```

Thank you in advance for your help.
Hallavar

**Comment by sniperyyc** [comment]
Hi Hallavar,

I did not run your config but something I spotted may be: You are using `iteration=500` and `"extra_checkpoint_freq": 20000` (500<20000) so you are not actually saving "an extra ckpt" for chunk0 to work as pre-trained models for later chunks. 

If you make the `extra_checkpoint_freq` smaller than your `iteration`, it should work. Anyway, I will get back to you with more answers after I tried it and a refactored codebase hopefully soon.

Thanks,
Yucheng

**Comment by hallavar** [comment]
Oh thank you, yeah that should be good. I reduced the number of iteration because I've wanted to check if the training runs correctly. I will try that.

**Comment by sniperyyc** [comment]
Sounds great. I noticed your comment in another issue and that may be a real problem -- I will try to get back to you on that front soon as well.

**Comment by hallavar** [comment]
Ok, so this was not the problem

I have reduced the number of vis_freq, and it seems to have solved it.
I can finish a training now.

**Comment by sniperyyc** [comment]
Ok, good to know. We have not used `vis_freq` for a while so not sure what happened on that front. I will close the issue for now.
