### ISSUE TITLE
The package can only be installed in ediable mode.

### ISSUE THREAD

**Issue by lurw2000** [netsharecmu/NetShare#2]
If the netshare package was installed through `pip3 install .` (without opening the editable option), I got the following error message when importing netshare:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import netshare
  File "/home/runwei/anaconda3/envs/netshare/lib/python3.6/site-packages/netshare/__init__.py", line 1, in <module>
    from .generators.generator import Generator
  File "/home/runwei/anaconda3/envs/netshare/lib/python3.6/site-packages/netshare/generators/generator.py", line 5, in <module>
    import netshare.pre_post_processors as pre_post_processors
  File "/home/runwei/anaconda3/envs/netshare/lib/python3.6/site-packages/netshare/pre_post_processors/__init__.py", line 2, in <module>
    from .netshare.netshare_pre_post_processor import NetsharePrePostProcessor
ModuleNotFoundError: No module named 'netshare.pre_post_processors.netshare'
```

**Comment by sniperyyc** [comment]
Hi, our current setup.py script only supports the editable installation. We will add the PyPI installation soon.
