### ISSUE TITLE
ValueError: result_folder: /data1/maoyuning/NetShare-master/results/test_caida/models/chunkid-1/sample_len-100 not found in configs!

### ISSUE THREAD

**Issue by MUNeng** [netsharecmu/NetShare#7]
I follow the instructions and run the scrip `driver.py`. The configuration is as follows:
```
{
    "global_config": {
        "original_data_file": "../traces/caida/raw.pcap",
        "dataset_type": "pcap",
        "n_chunks": 5,
        "dp": false
    },
    "model":{
        "class": "DoppelGANgerTFModel",
        "config": {
            "iteration": 10,
            "extra_checkpoint_freq": 5,
            "epoch_checkpoint_freq": 2
        }
    },
    "default": "pcap.json"
}

```
Here is the error message:
```
Traceback (most recent call last):
  File "driver.py", line 16, in <module>
    generator.train_and_generate(work_folder='/data1/maoyuning/NetShare-master/results/test_caida')
  File "/data1/maoyuning/NetShare-master/netshare/generators/generator.py", line 205, in train_and_generate
    if not self.generate(work_folder):
  File "/data1/maoyuning/NetShare-master/netshare/generators/generator.py", line 176, in generate
    work_folder)):
  File "/data1/maoyuning/NetShare-master/netshare/generators/generator.py", line 110, in _post_process
    log_folder=log_folder)
  File "/data1/maoyuning/NetShare-master/netshare/pre_post_processors/pre_post_processor.py", line 38, in post_process
    log_folder=log_folder)
  File "/data1/maoyuning/NetShare-master/netshare/pre_post_processors/netshare/netshare_pre_post_processor.py", line 500, in _post_process
    configs)
  File "/data1/maoyuning/NetShare-master/netshare/pre_post_processors/netshare/util.py", line 503, in _recalulate_config_ids_in_each_config_group
    config["result_folder"]))
  File "/data1/maoyuning/NetShare-master/netshare/model_managers/netshare_manager/netshare_util.py", line 77, in get_configid_from_kv
    raise ValueError("{}: {} not found in configs!".format(k, v))
ValueError: result_folder: /data1/maoyuning/NetShare-master/results/test_caida/models/chunkid-1/sample_len-100 not found in configs!

```

**Comment by sniperyyc** [comment]
Could you please share the driver code and the environment you are using as well? (operating system, cloud/single machine, with or w/o Ray) Thanks!

**Comment by MUNeng** [comment]
I'm running on a single machine(Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-148-generic x86_64) ) and turn Ray on.
The `driver.py` looks:
```
import netshare.ray as ray
from netshare import Generator

if __name__ == '__main__':
    # Change to False if you would not like to use Ray
    ray.config.enabled = True
    ray.init(address="auto")

    # configuration file
    generator = Generator(config="pcap/config_example_pcap_nodp_caida.json")

    # `work_folder` should not exist o/w an overwrite error will be thrown.
    # Please set the `worker_folder` as *absolute path*
    # if you are using Ray with multi-machine setup
    # since Ray has bugs when dealing with relative paths.
    generator.train_and_generate(work_folder='/data1/maoyuning/NetShare-master/results/test_caida')

    ray.shutdown()
```

**Comment by sniperyyc** [comment]
Thanks. We will take a look and get back to you soon.

**Comment by sniperyyc** [comment]
Feel free to try [the latest refactored PyTorch version](https://github.com/netsharecmu/NetShare) which includes the updated examples and reopen this issue if the bug persists.
